- azure/install_dependencies.sh
- azure/runnable_submodules.yml
- tests/test_data/inputtrain.yaml
- torchani/neurochem/__init__.py
I don't really know if you are interested in this. If not feel free to just close the PR. 
I just like config files in `yaml` as I find them more readable and they save you from defining a grammar or using lark.
Only thing it doesn't do is type check but I see that the lark definition is also quite flexible on the types.
I kept the lark parser in there just in case although this causes some obvious code duplication.
This is what the `yaml` file looks like although it's structure can be changed very easily.
https://gist.github.com/stefdoerr/47abc07538246a1b5026955453a83cdf
In the end I guess it's a personal taste issue so if you don't care for it or you didn't use yaml on purpose feel free to close this as I said :)
> Added a yaml construct method for Trainer

- .gitignore
- tests/test_aev.py
- tests/test_data.py
- tests/test_energies.py
- tests/test_ensemble.py
- tests/test_forces.py
- tests/test_ignite.py
- tests/test_structure_optim.py
- tools/inference-benchmark.py
- tools/neurochem-test.py
- tools/training-benchmark-with-aevcache.py
- tools/training-benchmark.py
- torchani/data/__init__.py
- torchani/data/cache_aev.py
- torchani/models.py
- torchani/neurochem/__init__.py
After speaking with Xiang today he told me that the Builtins and BuiltinsANI1CCX API was an old API that was put inside the new ANI1x and ANI1ccx API for convenience. 
This old API was confusing, since it was carried inside the ANI1x and ANI1ccx models and then the attributes of the old API were passed onto the models, it made the code hard to understand and there wasn't any reason behind it. There were 4 classes doing essentially redundant stuff.
Also, the names of the old API didn't make much sense anymore. For example, 
it wasn't clear that all the tests were using ANI1x. For maintainability reasons I thought it
would be a good idea to **get rid of all this baggage and make things simpler.** 
The old classes BuiltinsAbstract, Builtins, BuiltinsANI1ccx and BuiltinModels are all …
> Reformat the BuiltinModels and Builtins API to make them simpler and clearer

- torchani/utils.py
@farhadrgh, the dataset you dropped me when iterating we get something like:
`{'species': tensor<(1, ...)>, 'coordinates': tensor<(0, ...)>}`, this is an empty subset containing 0 conformations but with atom types well defined...
Originally TorchANI was assuming the number of conformations >= 1 and fails to load this dataset
This PR make TorchANI able to handle this case
> Support 0 molecule subsets when loading dataset

- azure/install_dependencies.sh
- azure/install_dependencies_python2.sh
- azure/python2.yml
The [last version](https://pypi.org/project/ase/3.17.0/) that has python2 support will be installed for python2 tests.
> ASE dropped python2 support

- docs/api.rst
- docs/conf.py
- torchani/models.py
The RTD theme has a bug with HTML5, right now the documentation is not being rendered properly if html4_writer is not enabeled, compare these:
This is the correct render with HTML5
This is the current render without HTML5
1) I enabeled the html4 writer
2) I fixed a docstring in the modules.py 
3) I removed Builtins from api.rst since the class no longer exists
> Small doc fixes

- tests/test_ignite.py
- tools/neurochem-test.py
- tools/training-benchmark.py
- torchani/data/__init__.py
- torchani/ignite.py
- torchani/neurochem/__init__.py
BatchedANIDataset class is deprecated but was still used internally by neurochem and in the tests and a bunch of other places, also load_ani_dataset was not included in the wildcard imports from torchani.data. This PR replaces all that with the new load_ani_dataset function.
> Replace BatchedANIDataset

- tests/test_aev.py
Currently there is a bug when an atom is isolated from its neighbors; when the neighbor list is empty 
AEVComputer crashes and raises IndexError. 
We had forgotten about this issue for a while so I made these tests that the current verision of torchani *fails*.
I made this to remind us that we have to fix this and to prevent this issue from arising again in the future.
Feedback is welcome!
> Add test for isolated atoms and large distances for 2 and 3 atoms

- examples/nnp_training.py
- examples/nnp_training_force.py
- examples/nnp_training_ignite.py
- torchani/data/__init__.py
- torchani/neurochem/__init__.py
Discard outlier energy conformers from the dataset prior to training. This is to replicate the same process in Neurochem, [here](https://github.com/Jussmith01/ANI-Tools/blob/9edc5a6a3740c0a93834effe15cdc6eecbaf3961/lib/anitraintools.py#L810) and [here]( https://github.com/Jussmith01/ANI-Tools/blob/9edc5a6a3740c0a93834effe15cdc6eecbaf3961/lib/anitraintools.py#L876).
> Discard outlier energy conformers

- torchani/aev.py
We compute a separate and smaller neighbor list when computing angular AEVs because Rca is usually much smaller than Rcr. This could reduce the time used to compute pairs of atoms, and now cutoff cosine could assume everything is inside cutoff radius, therefore no need for `torch.where`.
**Benchmark on ANI-1x full set epoch time:**
before: 325.12s
after: 273.06s
> Accelerate angular AEV computation and reduce memory cost

- tests/test_data.py
```py
self.assertEqual(coordinates.shape[1], coordinates.shape[1])
self.assertEqual(coordinates.shape[0], coordinates.shape[0])
```
should be 
```py
self.assertEqual(coordinates.shape[:2], species.shape[:2])
```
> fix typo in test_data.py

- tests/test_data_new.py
- tools/training-benchmark.py
- torchani/data/new.py
- other_properties (dict): A dict which is used to extract properties other than `energies` from dataset with correct padding, shape and dtype.
The example below will extract `dipoles` and `forces`.
- `padding_values`: set to `None` means there is no need to pad for this property.
```python
other_properties = {'properties': ['dipoles', 'forces'],
'padding_values': [None, 0],
'padded_shapes': [(batch_size, 3), (batch_size, -1, 3)],
'dtypes': [torch.float32, torch.float32]
}
```
- include_energies (bool): Whether include `energies` into properties. Default is `True`.
> New Dataset API add other properties

- torchani/utils.py
if I train molecule like Oxygen which contains only one element, the self.self_energies is a scalar and will make the operation self_energies = self.self_energies[species] crash. Besides, the species of Oxygen is [[3,3]] and is over the boundary of the energy list, so need to minus the minimum.
> Fix the dimension in self_energies for dataset containing only one elements

- .github/workflows/unittest.yml
By default, GitHub cancels all in-progress jobs if any `matrix` jobs fail in Actions. This PR will change the default to let all the tests running in case one of them fails.
> Keep in-progress jobs once a test fails in Actions

- tests/test_forces.py
JIT uses symbolic differentiation (autodiff), which is different from autograd. Autodiff might be buggy, we need to make sure no bugs in autodiff influence TorchANI.
> Add force to unittest of JIT

- torchani/data/__init__.py
This hopefully is the last fix to make the process of discarding outlier energies identical to NeuroChem.
> Fix the lower/upper bounds to discard outliers

- tools/comp6.py
- torchani/utils.py
I wonder why the test hadn't failed before!
> Fix dtype in self_energies

- .github/workflows/deploy-test-pypi.yml
- .github/workflows/docs.yml
- .github/workflows/flake8.yml
- .github/workflows/python2.yml
- .github/workflows/runnable_submodules.yml
- .github/workflows/tools.yml
- .github/workflows/unittest.yml
We need to trigger the GitHub Actions on `pull_request` instead of `push`
>  [When a pull request is submitted from a forked repository to the base repository, GitHub sends the `pull_request` event to the base repository and no pull request events occur on the forked repository](https://help.github.com/en/github/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories).
> Trigger Actions on pull_request instead of push

- torchani/aev.py
`triu_index` is using `cpu`. Now casting the results to cuda device if needed.
> Fix CUDA support in AEVComputer

- torchani/models.py
Specifying type inside a comment is stupid and should be removed
> Use modern type annotations for models.py

- .github/workflows/docs.yml
When the 3.6 and 3.7 docs build tries to push at the same time, one of the might fail
> Fix race condition in test docs deploy

- torchani/nn.py
Subclassing was the way things were implemented, but when we add JIT support, we have to change it to be JIT-compatible. Now https://github.com/pytorch/pytorch/pull/28988 is coming soon and it's time to bring the original implementation back.
> Subclass ModuleList to simplify code

- .github/workflows/unittest.yml
- tests/test_nn.py
- tools/comp6.py
- torchani/__init__.py
- torchani/models.py
- torchani/nn.py
This also includes some cleanups.
With this PR, users still need to manually add `SpeciesConverter` to their pipeline. Support for `torchani.models` will be added in later PR.
> Add helper module to convert species from element id in periodic table to 0, 1, 2, 3, ... format

- torchani/data/new.py
Error happend at truncating redundant padding.
```
File "../ANI_D/data.py", line 569, in collate_fn
chunks_batch_coordinates[i] = c.reshape(c.shape[0], -1, 3)
RuntimeError: shape '[115, -1, 3]' is invalid for input of size 15410
```
by change padding value to np.inf
> Fix new dataset API coordinates reshape bug

- examples/vibration_analysis.py
- tests/test_vibrational.py
- torchani/utils.py
Maybe you are interested in this, I did this to do sampling with torchani, and I realized I needed Gaussian-Style normal modes and force constants in order to do this, I think this may be useful
> Now vibrational analysis includes reduced masses, force constants and normalized modes

- .github/workflows/deploy-test-pypi.yml
- .github/workflows/docs.yml
GitHub secrets are not available on forked repositories, causing flaky failures on forked repositories, such as https://github.com/aiqm/torchani/pull/413 and https://github.com/aiqm/torchani/pull/393. I have force merged these PRs, but we need to skip these failing tests on forked repositories.
Reference: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables#default-environment-variables
```
GITHUB_HEAD_REF | Only set for forked repositories. The branch of the head repository.
```
> Fix failure on forked repository

- examples/nnp_training.py
- examples/nnp_training_force.py
- tests/test_utils.py
- tools/training-benchmark-nsys-profile.py
- tools/training-benchmark.py
- torchani/utils.py
We came to know that some people had bugs in their code because they input strings like 'CHNClFeCu' into ChemicalSymbolsToInts instead of ['C', 'H', 'N', 'Cl', 'Fe', 'Cu']. This PR adds a warning to ChemicalSymbolsToInts and changes ocurrences of ['CHNO'] to ['C', 'H', 'N', 'O'] in the code, to encourage safer use of the class.
> ChemicalSymbolsToInts is being used wrong

- tests/test_ase.py
- torchani/ase.py
- torchani/models.py
This fixes a bug I found where the ASE interface can't be used together with periodic_table_index=True
It also adds a test so that this doesn't happen again
> Fix periodic table index ase

- torchani/aev.py
This PR fixes a small error introduced in #420. `default_shifts` calculated by `compute_shifts()` is used in case of nopbc and has zero elements.
> Fix aev.neighbor_pairs_nopbc

- .gitignore
- examples/nnp_training.py
- examples/nnp_training_force.py
- tests/test_data.py
- torchani/data/__init__.py
- torchani/utils.py
The new suggested way to use dataset is:
```Python
training, validation = torchani.data.load(dspath).subtract_self_energies(energy_shifter).species_to_indices().shuffle().split(0.8, None)
training = training.collate(batch_size).cache()
validation = validation.collate(batch_size).cache()
```
which is cleaner than the previous
```Python
dataset = torchani.data.load(dspath).subtract_self_energies(energy_shifter).species_to_indices().shuffle()
size = len(dataset)
training, validation = dataset.split(int(0.8 * size), None)
training = training.collate(batch_size).cache()
validation = validation.collate(batch_size).cache()
```
The memory usage has reduced from the previous 18GB to 16GB, this is a small improvement, but it is hard to make it as good as the previously API by @yueyericardo because …
> Improve more on new dataset API

- examples/nnp_training.py
- examples/nnp_training_force.py
AEV dimension does not need to be hardcoded. This will be helpful when we include ANI2x networks, i.e. when training with models different number of species than 4.
> AEV dimension from aev_computer

- torchani/aev.py
`zeros_like` is not free. It needs to launch a kernel to fill 0 to all the elements.
> Take advantage of torch.where broadcasting

- torchani/utils.py
PyTorch has supported type promotion since the last PTDC. We shouldn't manually convert the dtype now because this has unnecessary memory access.
> Make use of PyTorch's type promotion logic to reduce memory access

- torchani/data/__init__.py
SAEs were sorted by the letters of species, whereas `EnergyShifter` expects a list that is sorted based on the indices assigned by `species_to_indices` transformation. This PR fixes the way we sort the SAEs before passing them to `EnergyShifter`.
> Fix order of SAEs in subtract_self_energies transform

- examples/nnp_training_force.py
- tests/test_jit_builtin_models.py
- torchani/data/__init__.py
This will help to save ~4GB memory when loading ANI1x data for energy training.
> Avoid loading/padding forces when not needed

- torchani/utils.py
Now I understand why PyTorch pin their version of flake8 in their CI. Sometimes flake8 updates and previously passing files become failing.
> fix flake8

- torchani/models.py
When using the model in a C++ environment, ``model.to(torch::kDouble)`` converts all Parameters AND all buffers to double. As a consequence all torch.long buffers in the model are converted to torch.double, which we definitely don't want. 
After this it becomes a hassle to specifically convert named buffers into doubles, I didn't find anything in the C++ API that exposed a handle to a ``torch::jit::script::Module`` buffer, so the workaround is to add a function that recasts the torch.long buffers to double once again on the python side
I'm not sure if this is a feature or a bug of libtorch, but I think it differs from the python behaviour
Sorry for the long explanation but this is complex.
> Add a function to recast all buffer tensors

- tests/test_periodic_table_indexing.py
- torchani/models.py
I don't like the current implementation of BuiltinNet, also I'm pretty sure noone likes the name. 
It is not really possible to add @torch.jit.export functions to the individual models inside a BuiltinNet, which is inconvenient for me, so I refactored it this way. I got rid of most of the internal attributes since they were not really useful. 
I wanted to know your opinion.
> Refactor builtinnet

- tests/test_ase.py
- tests/test_energies.py
- tests/test_forces.py
- tests/test_structure_optim.py
- torchani/models.py
This PR builds on my previous PR and allows easily loading single models without loading the 
whole network using 
``single_model = ANI1x(model_index=0)``
``ensemble = ANI1x()``
for example.
> Allow easily loading individual models 

- examples/nnp_training.py
- examples/nnp_training_force.py
- torchani/data/__init__.py
species_to_indices allows arbitrary order but subtract_self_energies does not.
I changed the code to make both functions "periodic_table_index" by default, but to allow arbitrary order if specifically asked to maintain compatibility with the rest of the code. Also, I changed the examples to reflect this
> Fix subtract energies 

- .gitignore
- tests/test_data.py
- tests/test_neurochem.py
- tests/test_vibrational.py
Added some very small cleanup to tests. Now test_neurochem always creates tensorboard outputs in /tests/ and all pickle files are cleaned up after vibrational_analysis is performed. Also added code coverage to gitignore
> Cleanup tests

- torchani/data/__init__.py
This adds an optional argument to collate_fn to add to address @plin1112 issue #458 and adds that to the documentation.
> Add possibility to use custom padding (address issue #458) 

- tests/test_data.py
This adds the test @farhadrgh asked me to do in #485 . I currently hardcoded the numbers to the current output of the EnergyShifter for `ani-1x/sample.h5` which is not very elegant but should be correct, recommendations appreciated.
> Add new test with hardcoded saes (address issue #485)

- README.md
- torchani/models.py
- torchani/resources/README.md
The model parameters for ANI2x and ANI1ccx have been moved out of TorchANI repo to another repository: https://github.com/aiqm/ani-model-zoo (https://github.com/aiqm/torchani/pull/481).
Although they will be automatically downloaded once the Built-in functions are called, we need to inform people where to look for them.
> README for resources

- .github/workflows/unittest.yml
- tests/test_aev.py
- tests/test_grad.py
- torchani/data/__init__.py
This PR adds two new tests, testGradCheck and testGradGradCheck, which are done in a way that 
are actually feasible in CPU and CUDA (tests take in total ~4 s in CPU). Currently these tests pass.
This PR deletes testGradient which was essentially never run since it was skipped by github and also always failed.
The issue was nondet_tol which was set to zero but shouldn't be, since many pytorch operations we perform use atomic_add and
similar nondeterministic ops internally, which means two inputs have very slightly different outputs. Also this test was incredibly slow.
> Fix gradcheck test

- torchani/data/__init__.py
For some reason, sometimes species are constructed as int tensors instead of long tensors, this is wrong and should be fixed
> Specify dtype for species

- torchani/utils.py
torch.norm is deprecated and may be removed in a future PyTorch release
fixes #514
> Use torch.linalg.norm instead of torch.norm

- torchani/aev.py
because it is faster.
Before:
```
torchani.aev.cutoff_cosine - 2.0s
torchani.aev.radial_terms - 0.7s
torchani.aev.angular_terms - 6.1s
torchani.aev.compute_shifts - 0.0s
torchani.aev.neighbor_pairs - 0.0s
torchani.aev.neighbor_pairs_nopbc - 1.9s
torchani.aev.triu_index - 0.0s
torchani.aev.cumsum_from_zero - 0.5s
torchani.aev.triple_by_molecule - 3.4s
torchani.aev.compute_aev - 15.8s
Total AEV - 15.8s
NN - 4.1s
Epoch time - 30.3s
```
After:
```
torchani.aev.cutoff_cosine - 1.6s
torchani.aev.radial_terms - 0.7s
torchani.aev.angular_terms - 5.6s
torchani.aev.compute_shifts - 0.0s
torchani.aev.neighbor_pairs - 0.0s
torchani.aev.neighbor_pairs_nopbc - 1.8s
torchani.aev.triu_index - 0.0s
torchani.aev.cumsum_from_zero - 0.5s
torchani.aev.triple_by_molecule - 3.3s
torchani.aev.compute_aev - 15.0s …
```
> Use handwritten cosine similarity

- torchani/aev.py
Because nan < number is always false.
Benchmark
Before
```
torchani.aev.cutoff_cosine - 0.1s
torchani.aev.radial_terms - 0.2s
torchani.aev.angular_terms - 0.6s
torchani.aev.compute_shifts - 0.0s
torchani.aev.neighbor_pairs - 0.0s
torchani.aev.neighbor_pairs_nopbc - 1.9s
torchani.aev.triu_index - 0.0s
torchani.aev.cumsum_from_zero - 0.1s
torchani.aev.triple_by_molecule - 2.5s
torchani.aev.compute_aev - 6.6s
Total AEV - 6.6s
NN - 13.0s
Epoch time - 29.6s
```
vs
After
```
torchani.aev.cutoff_cosine - 0.1s
torchani.aev.radial_terms - 0.2s
torchani.aev.angular_terms - 0.6s
torchani.aev.compute_shifts - 0.0s
torchani.aev.neighbor_pairs - 0.0s
torchani.aev.neighbor_pairs_nopbc - 1.7s
torchani.aev.triu_index - 0.0s
torchani.aev.cumsum_from_zero - 0.1s
torchani.aev.triple_by_molecule - 2.4s …
```
> Simplify pair computation on AEV

- docs/api.rst
- examples/jit.py
- examples/vibration_analysis.py
- tests/test_utils.py
- tests/test_vibrational.py
- torchani/utils.py
PyTorch now officially supports `torch.autograd.functional.hessian`, so there is no need to implement `hessian` in TorchANI, and `vibrational_analysis` should be adjusted to support the hessian returned by `torch.autograd.functional.hessian`.
> Use PyTorch autograd's hessian

- torchani/nn.py
- torchani/utils.py
* Change 0th index of periodic table
* Change species converter to reflect new convention
* Change None for 'Dummy' and fix flake8
> Cherry-pick roitberg-group#23

- .github/workflows/unittest.yml
- .gitignore
- examples/energy_force.py
- tests/test_al.py
- torchani/models.py
- torchani/nn.py
* Add convenience functions useful for active learning
* avoid training outputs
* modify gitignore
* Add convenience functions to directly get atomic energies
* fix bug
* fix mypy
* flake8
* fix bugs
* flake8
* mypy
* Add tests for functions
* add test to workflows and flake8
* empty to trigger tests
* trigger
* delete new test
* readd new test
* avoid training outputs
* trigger
* trigger tests again, they are all passing on my side
* fix isclose in tests
> Cherry-pick roitberg-group#10

- tests/test_cuaev.py
- torchani/cuaev/aev.cu
When center atom pairs are more than 32 (never happended at ani1x dataset), angular kernel didn't iterate over `kk_start`.
Test:
Before: 
```
AssertionError: False is not true : Tensors failed to compare as equal! With rtol=5e-05 and atol=5e-05, 
found 3952 element(s) (out of 22272) whose difference(s) exceeded the margin of error (including 0 nan comparisons). 
The greatest difference was 347.97611236572266 (50.77568817138672 vs. 398.7518005371094), which occurred 
at index (0, 38, 97).
```
The error is gone after this fix.
cc @akkamesh
> Fix cuaev angular kernel bug when center atom pairs are more than 32

- tests/test_aev.py
- torchani/aev.py
Handwritten cosine similarity outputs NaN values for superimposed coordinates due to the singularity in v1 dot v2 / ||v1|| * ||v2|| when one of the vectors has zero distance. 
Sometimes, during an MD simulation with many many many atoms, 2 atoms are randomly pushed to the same coordinate value.
When this happens torchani outputs NaN as an energy and the simulation breaks.
With clamp:
```
torchani.aev.cutoff_cosine - 0.2s
torchani.aev.radial_terms - 0.3s
torchani.aev.angular_terms - 0.8s
torchani.aev.compute_shifts - 0.0s
torchani.aev.neighbor_pairs - 0.0s
torchani.aev.neighbor_pairs_nopbc - 3.7s
torchani.aev.triu_index - 0.0s
torchani.aev.cumsum_from_zero - 0.1s
torchani.aev.triple_by_molecule - 3.2s
torchani.aev.compute_aev - 9.9s
Total AEV - 10.0s
Forward - 18.1s
Backward - 4.0s …
```
> Fix handwritten cosine similarity and add test for NaNs in AEVComputer

- torchani/neurochem/parse_resources.py
Hi,
We're running TorchANI in an environment where the python packages are mounted in a read-only directory. `_parse_neurochem_resources` attempts to extract resources into the package directory and this raises a OSError for us. There's already handling for writing to a local folder in the home directory when a PermissionError is raised; this pull request applies the same handling to the OSError case as well and fixes this issue for us. 
Thanks!
> handle OSError in parse_neurochem_resources

- torchani/data/__init__.py
Current behavior of `shuffle()` and `cache()` is not very performant since calling `dataset.cache().shuffle()`, `dataset.cache().cache()`, `dataset.shuffle().shuffle()` or other combinations creates copies instead of letting the arguments go through if the input is already cached, which is costly for no reason.
I also fixed a couple of typos in the documentation.
> improve documentation and fix buggy behavior of shuffle() and cache()

- setup.py
- torchani/cuaev/aev.cu
nvcc<11 does not have (if constexpr) c++17 feature, which will lead to compilation failed on cuda versions < 11.0
> [CUAEV] Remove (if constexpr) c++17 feature

- tests/test_cuaev.py
fixes #618 by adding keyword arguments to `make_tensor` in `testAEVComputer`
> add keyword arguments to testAEVComputer

- torchani/ase.py
- torchani/utils.py
This PR fixes an issue with `torch.symeig`, which is now deprecated. Instead, it is suggested to work with `torch.linalg.eigh`
> Fixed: symeig deprication

- setup.py
I updated setup.py to add cuda archs for latests versions.
Also added c++17 when compiling with pytorch>= 2.1.
I removed the logic to download cub, it is bundled with CUDA via thrust since some versions ago.
I used this PR as a patch here for the conda-forge feedstock here https://github.com/conda-forge/torchani-feedstock/pull/24
> Set C++17 for latest pytorch versions. Add flags for CUDA 12 and 11.8
