docs/conf.py
setup.py
torchani/__init__.py

https://github.com/aiqm/torchani/issues/140

Automatic versioning

---

torchani/ignite.py

https://github.com/pytorch/ignite/pull/300
https://github.com/aiqm/torchani/issues/141

Remove MaxAE from TorchANI

---

README.md
docs/api.rst
docs/start.rst

Related to: https://github.com/aiqm/torchani/issues/162
PyTorch should be installed by pip instead of conda.

Fix docs about installation

---

tests/test_ase.py
tests/test_structure_optim.py
tools/generate-unit-test-expect/structure-optim.py
torchani/ase.py

And improve test coverage on ASE interface

Fix ASE interface when box size is 0

---

torchani/utils.py

Fixes: https://github.com/aiqm/torchani/issues/183

Use .item() instead of type cast

---

examples/ase_interface.py
tests/test_ase.py
torchani/aev.py
torchani/ase.py
torchani/models.py

Fixes: https://github.com/aiqm/torchani/issues/190
cc: @LeanAndMean

Change default dtype of ase to float64

---

tests/test_aev.py

This test currently fails when running on a CUDA device.

Added finite differences gradient check for aev_computer.

---

torchani/aev.py

Use the new torch.unique_consecutive to speedup

---

dataset/ani-1x/sample.h5
torchani/data/__init__.py

Also add a small sample of ANI-1x

Refactor cache_aev and cache_sparse_aev

---

torchani/data/__init__.py

This is to prepare for supporting a big dataset into subsets.

Move core function of BatchedANIDataset.__init__ outside

---

dataset/ani-1x/sample.h5
docs/index.rst
examples/nnp_training.py
examples/nnp_training_force.py

Not benchmarked yet. Will merge first, and maybe fix later.

Add example for force training

---

CODEOWNERS

Hi @farhadrgh, I am adding you as a code owner of `/torchani/data` since you have experience on this. Later I will request your review if there are PR changing that part.

Add @farhadrgh to code owner of /torchani/data

---

torchani/aev.py

Rename input->input_ to avoid name clash

---

CODEOWNERS

@farhadrgh Please review and merge
After this get merged, I will set branch protection policy to "require code owner review", i.e. everyone's code, including mine, need to be reviewed before being able to merge.

Add @farhadrgh as a code owner for everything

---

examples/nnp_training.py

- Weight initialization to Kaiming normal with a=1
- Biases initialized to zeros
- exponential loss is removed from the training process
- The pretraining loop is removed

nnp_training updated

---

examples/nnp_training_force.py

Force coefficient is better to be 0.1

---

torchani/data/_pyanitools.py

Change unidiomatic type calls to isinstance and remove deprecated h5py operator

---

torchani/optim.py

I have noticed a couple of discrepancies between theory and the implementation of AdamW and in general Adam:
1. In the case of Adam with decoupled weight decay (AdamW), the weight-decay update should be performed before updating the parameters [(Algorithm 2, L6)](https://arxiv.org/pdf/1711.05101.pdf).
2. The epsilon in the denominator of the following Adam update should not be scaled by the bias correction [(Algorithm 2, L9-12)](https://arxiv.org/pdf/1711.05101.pdf). Only the running average of the gradient (_m_) and squared gradients (_v_) should be scaled by their corresponding bias corrections.
In the current implementation, the epsilon is scaled by the square root of `bias_correction2`.  I have plotted this ratio as a function of step given `beta2 = 0.999` and `eps = 1e-8`. In the …

AdamW implementation minor fix

---

torchani/data/_pyanitools.py
torchani/ignite.py

Since I got a codefactor warning in my previous PR I checked the warnings we have and it seems that most come from Justin's docstrings which are written in C-style on top of functions instead of under them.
I fixed this so that we don't have many useless codefactor warnings and we can focus on the useful ones.

Fix codefactor warnings

---

examples/nnp_training.py
examples/nnp_training_force.py
tests/test_aev.py
torchani/aev.py
torchani/ase.py
torchani/data/__init__.py
torchani/ignite.py

Also fixes: https://github.com/aiqm/torchani/issues/276

Port to torch.bool data type where it should be

---

examples/nnp_training.py

This PR fixes #243 
Make `nnp_training.py` setup identical to Neurochem.
- Fixed docs, removed warnings
- SGD added
- Removed 1st layer's weight decay parameters

Update nnp_training to have identical setup to NC

---

setup.py

add description to https://pypi.org/project/torchani/

enable description in pypi page

---

tests/test_aev.py

Small fix in a test which had a missing atom

small fix in methane, had a missing atom

---

README.md
azure/deploy-docs.yml
azure/docs.yml
azure/install_dependencies.sh
azure/install_dependencies_python2.sh
azure/runnable_submodules.yml
azure/tools.yml
docs/start.rst
setup.py

`torch-nightly` has been renamed to `torch`

Fix dependency in setup.py: `torch-nightly` has been renamed to `torch`

---

tests/test_energies.py
torchani/utils.py

This PR fixes one of the items in #305

[JIT] Add TorchScript Compatibility for EnergyShifter

---

.github/workflows/unittest.yml

It seems that git's automatic merge mess things up...

Fix unittest.yaml

---

tools/training-benchmark-nsys-profile.py

Nsight System is super powerful:
We don't have GPUs in our CI, so not testing it.

Add script for profiling training on NVIDIA GPUs using Nsight System

---

.github/workflows/deploy-docs.yml
.github/workflows/deploy-pypi.yml
.github/workflows/deploy-test-pypi.yml
.github/workflows/docs.yml
README.md

- New test named `deploy-test-pypi` is added. This test runs on PR and try to deploy to testing PyPI repo
- In docs action, try to deploy to https://github.com/aiqm/torchani-test-docs
- new actions: `deploy-docs` and `deploy-pypi` to do the actual deployment

Deploy scripts using GitHub Actions

---

README.md

@farhadrgh I will make a new release after this get merged.

Update badge for deployment

---

torchani/utils.py

Fix dtype of energies returned from energy_shifter 

---

torchani/nn.py
torchani/utils.py

Fix CUDA support in ANIModel and EnergyShifter 

---

README.md
docs/start.rst

My PyTorch is installed using conda, it is no longer a problem now.

Remove outdated warnings

---

torchani/aev.py

I love the syntax of using `@` as a matrix multiply. I have been dreaming of using it for a year and now my dream finally comes true.
Python 2 go to die

Use @ syntax for matrix multiply

---

torchani/nn.py

Specifying type inside a comment is stupid and should be removed

Use modern type annotations for nn.py

---

torchani/aev.py

And the new suggested syntax is using python 3 type annotation

__constants__ is deprecated by torch.jit

---

ci/install_dependencies.sh
tests/test_structure_optim.py

~~Just to see if ASE fixes its bug. If yes, please merge.~~
This is not an ASE bug, but ASE does not support loading objects pickled from its older version.

Fix tests for latest ASE

---

torchani/ase.py

It should be just as simple as a matrix multiply

Improve analytical stress calculation

---

examples/energy_force.py
torchani/aev.py
torchani/models.py
torchani/nn.py

Fixes https://github.com/aiqm/torchani/issues/388

Docs about unit

---

examples/jit.py
torchani/models.py

Please check the rendering of docs at https://aiqm.github.io/torchani-test-docs/ before merge

Add example to customize JIT models

---

torchani/ase.py

Fixes https://github.com/aiqm/torchani/issues/408

Fix force shape when only 1 atom

---

torchani/ase.py

This PR resolves #415
Thanks @mhellstr for pointing it out

Add retain_graph (force and stress) case in ASE

---

torchani/aev.py

This should improve performance of AEV calculation by 7-5% for typical molecule sizes.

Slight improvement in performance of AEV

---

torchani/aev.py

I believe this still has issues so better not merge this at this point, I'm opening the PR to see if all tests pass, etc, since there are tests I'm too lazy to run

bypass slow code

---

tools/training-benchmark.py

Adding synchronize gives more accurate microbenchmark, but less accurate end to end performance benchmark.

Add an argument for inserting synchronization

---

examples/nnp_training.py
tools/training-benchmark.py

Massive training time improvement by doing a simple substitution in nnp_training

massive training time improvement

---

torchani/data/__init__.py

- Fix a progress bar display bug
- Reduce memory usage
With this PR, data loading takes ~7.5GB CPU RAM
In the next PR, I will adopt a new shuffle algorithm to further reduce the memory usage

Improve new dataset API

---

tools/training-benchmark.py

ANI1x NNs are updated to be consistent with what we used in the paper

Update NN in training benchmark

---

torchani/nn.py

SpeciesConverter returns species on same device as input

---

examples/load_from_neurochem.py

People keep having issues with this so I hunted this one down and changed it.

Make input more clear in example

---

torchani/data/__init__.py
torchani/models.py
torchani/nn.py
torchani/utils.py

I clarified as much as possible, please check for any mistakes.

Document data

---

.github/workflows/deploy-pypi.yml
.github/workflows/deploy-test-pypi.yml

Fixes https://github.com/aiqm/torchani/issues/507

Distribute source tarball and wheel to PyPI

---

torchani/aev.py

Fix typo in aev.py

---

torchani/aev.py
torchani/models.py
torchani/nn.py

Raise error for unknown species

---

.github/workflows/cuda.yml

Set paths for cuda test to avoid it got triggerd in every push, which takes about 16 min.

Set paths for cuda test to avoid it got triggerd in every push

---

torchani/ase.py
torchani/models.py
torchani/nn.py
torchani/utils.py

* delete all python2 style super calls
* flake8

Cherry-pick roitberg-group#14

---

tools/training-benchmark.py

* Make training benchmark print a warning if not synchronizing, and add a sync before function also
* Take triu_index out since it does not run
* slightly increase default precision
* flake8

Cherry-pick roitberg-group#17

---

docs/api.rst
examples/jit.py
examples/vibration_analysis.py
tests/test_utils.py
tests/test_vibrational.py
torchani/utils.py

Revert "Use PyTorch autograd's hessian"

---

tests/test_energies.py
torchani/aev.py
torchani/nn.py

* commit farhads and jinzes changes to fix some bugs
* Add tests for correct inputs

Cherry-pick roitberg-group#22

---

.gitignore
examples/nnp_training.py

This should help with issue #443 , I had some people tell me they were not sure how to do this so I guess it doesn't hurt to add something like this.

Add code snippet to save validation and training sets in nnp_training

---

.clang-format
torchani/cuaev/aev.cu

clang-format line-limit to 120

---

examples/nnp_training.py
examples/nnp_training_force.py

Deactivate autograd engine for validation examples and add model.train(False) and model.train(True) for future insurance

deactivate autograd during validation

---

.clang-format
tests/test_cuaev.py
torchani/cuaev/aev.cu

Try to implement backward for cuaev.

CUAEV backward

---

torchani/cuaev/aev.cu

The value can be computed on the fly in O(1) time, this saves memory read and memory copy

Remove constant memory usage

---

.github/workflows/cuda.yml
ci/install_cuda.sh
setup.py

Speedup cuda ci by only install necessary nvcc tools

CI cuda test speedup

---

tests/common_aev_test.py
tests/test_aev.py
tests/test_al.py
tests/test_ase.py
tests/test_data.py
tests/test_energies.py
tests/test_ensemble.py
tests/test_forces.py
tests/test_grad.py
tests/test_jit_builtin_models.py
tests/test_neurochem.py
tests/test_padding.py
tests/test_periodic_table_indexing.py
tests/test_structure_optim.py
tests/test_utils.py
tests/test_vibrational.py
torchani/__init__.py

Remove annoying warning of 
```
Fail to import hypothesis in common_utils, tests are not derandomized
```

remove test warning

---

torchani/utils.py

Credit: codes from: @IgnacioJPickering

[Bug] Fix JIT Could not cast attribute 'rev_species' to type Dict[Tensor, int]

---

tests/test_cuaev.py
tests/test_energies.py
torchani/cuaev/aev.cu

Fix AEV and CUAEV Multi-GPU Device Bug

---

tests/test_cuaev.py
torchani/cuaev/cuaev.cpp

code from internal to fix https://github.com/aiqm/torchani/issues/598#issuecomment-959004422

cuaev def_pickle
